apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi-deployment
  labels:
    app: userapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userapi
  template:
    metadata:
      labels:
        app: userapi
    spec:
      containers:
      - name: userapi
        image: rvhromov/userapi:latest
        env:
        - name: DatabaseSettings__Server
          valueFrom:
            configMapKeyRef:
              name: mssql-config
              key: mssql-host
        - name: DatabaseSettings__Catalog
          valueFrom:
            configMapKeyRef:
              name: mssql-config
              key: mssql-catalog
        - name: DatabaseSettings__UserId
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: mssql-userid
        - name: DatabaseSettings__Password
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: mssql-password
---
apiVersion: v1
kind: Service
metadata:
  name: userapi-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: userapi
  ports:
    - name: userapi
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: userapi-nodeport-service
spec:
  type: NodePort
  selector:
    app: userapi
  ports:
    - name: userapi
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100