apiVersion: apps/v1
kind: Deployment
metadata:
  name: beerapi-deployment
  labels:
    app: beerapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beerapi

  # pod configuration
  template:
    metadata:
      labels:
        app: beerapi
    spec:
      containers:
      - name: beerapi
        image: rvhromov/beerapi:latest
        env:
        - name: DatabaseSettings__User
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: DatabaseSettings__Password
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        - name: DatabaseSettings__Host
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-host
---
apiVersion: v1
kind: Service
metadata:
  name: beerapi-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: beerapi
  ports:
    - name: beerapi
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: beerapi-nodeport-service
spec:
  type: NodePort
  selector:
    app: beerapi
  ports:
    - name: beerapi
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000